apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: public-namespace-rolebinding
  namespace: public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: public-namespace-full-access-role
subjects:
  - kind: User
    name: eks-user
    apiGroup: rbac.authorization.k8s.io
